name: app setup

on:
   workflow_dispatch:
    
jobs:
    folder-setup:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        runs-on: ${{ vars.GHA_UBUNTU_RUNNER }}
        env:
            HOST: ${{ vars.DEPLOY_HOST }}
            USER: ${{ vars.SETUP_USER }}
            PORT: ${{ vars.DEPLOY_PORT }}
            SSH_KEY: ${{ secrets.SETUP_SSH_KEY }}
            LOG_VOLUME: "${{ vars.DATA_VOLUME }}/data/app/logs"
        steps:
        - name: ssh setup
          run: |
            mkdir -p "$HOME/.ssh"
            KEY_FILE="$HOME/.ssh/id_ed25519"

            echo "${SSH_KEY}" > "$KEY_FILE"

            echo "SSH_KEY_FILE=$KEY_FILE" >> "$GITHUB_ENV"

            chmod 400 "$KEY_FILE"
        - name: checkout code
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # @v6
          with:
            fetch-depth: 0
            persist-credentials: false

        - name: folder setup
          shell: bash
          run: |

            DATA_VOLUME=$(echo "$LOG_VOLUME" | tr -d '\r')

            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -p ${PORT} -i ${SSH_KEY_FILE} ${USER}@${HOST} "LOG_VOLUME='${LOG_VOLUME}' bash -s" << 'EOF'
            sudo mkdir -p ${LOG_VOLUME:?ERROR LOG_VOLUME NOT SET}
            sudo chmod -R 0777 ${LOG_VOLUME}

            exit
            EOF                    