name: celery deploy

on:
   workflow_dispatch:

  
    
jobs:
    celery-deploy:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        runs-on: ${{ vars.GHA_UBUNTU_RUNNER }}
        env:
            STACK_NAME: ${{ vars.STACK_NAME }}
            STACK: "${{ vars.STACK_NAME }}"
            APP_IMAGE: "${{ vars.APP_IMAGE }}"
            CELERY_HOST: ${{ vars.CELERY_HOST }}
            REDIS_HOST: ${{ vars.REDIS_HOST }}
            REDIS_PORT: ${{ vars.REDIS_PORT }}
            DOCKER_STACK_FILE: "deploy/celery/celery-compose.yml"
            HOST: ${{ vars.DEPLOY_HOST }}
            USER: ${{ vars.SETUP_USER }}
            SSH_KEY: ${{ secrets.SETUP_SSH_KEY }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DEBUG: False  # always set this to False on staging & production environments
            ALLOWED_HOST: ${{ vars.ALLOWED_HOST }}
            FRONTEND_BASE_URL: ${{ vars.FRONTEND_BASE_URL }}
            PORT: ${{ vars.DEPLOY_PORT }}
            LOGS_DIR_PATH: ${{ vars.LOGS_DIR_PATH }}
            DJANGO_ENV: ${{ vars.DJANGO_ENV }}
            POSTGRES_USER: ${{ vars.POSTGRES_USER }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB }}
            POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
            POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
            # PARTNER_PORTAL_WEBHOOK_URL=<partner portal app webhook>
            # POSTGRES_USER=<database user>
            # POSTGRES_PASSWORD=<database password>
            # POSTGRES_HOST=<database host>
            # POSTGRES_PORT=<database port>
            # POSTGRES_DB=<database name>
            # POSTGRES_SSLMODE=require  # set this to require

            # MAILTRAP_TOKEN=<mailtrap token>
            # EMAIL_SENDER=<mailtrap sender name>
            # EMAIL_SENDER_NAME=<mail title/header>
        steps:
        - name: checkout code
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # @v6
          with:
            fetch-depth: 0
            persist-credentials: false

        - name: ssh setup
          run: |
            mkdir -p "$HOME/.ssh"
            KEY_FILE="$HOME/.ssh/id_ed25519"

            cat << 'EOF' > "$KEY_FILE"
            ${{ env.SSH_KEY }}
            EOF

            echo "SSH_KEY_FILE=$KEY_FILE" >> "$GITHUB_ENV"
            chmod 400 "$KEY_FILE"
                 
        - name: stack config
          shell: bash
          run: |
           
            envsubst < "${DOCKER_STACK_FILE}" | docker stack config -c -
        
        - name: ghcr login
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: stack deploy
          shell: bash
          run: |
            mkdir -p "$HOME/.ssh"
            cat << EOL > "$HOME/.ssh/config"
            Host ngrok-vbt
                HostName ${HOST}
                Port ${PORT}
                User ${USER}
                IdentityFile ${SSH_KEY_FILE}
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null
            EOL

            export DOCKER_HOST="ssh://ngrok-vbt"
            
            ssh ngrok-vbt "sudo mkdir -p ${LOGS_DIR_PATH} && sudo chmod -R 777 ${LOGS_DIR_PATH}"

            docker network inspect ${STACK_NAME}_infra-net >/dev/null 2>&1 || \
            docker network create --driver overlay ${STACK_NAME}_infra-net
                      
            envsubst < "${DOCKER_STACK_FILE}" | docker stack deploy --with-registry-auth -c - "${STACK_NAME}"
            docker stack ls
            docker stack ps "${STACK_NAME}"