name: postgres deploy

on:
   workflow_dispatch:
    
jobs:
    postgres-deploy:
        if: ${{ github.event_name == 'workflow_dispatch' }}
        runs-on: ${{ vars.GHA_UBUNTU_RUNNER }}
        env:
            STACK_PREFIX: "prod"
            STACK_NAME: "prod-admin-portal"
            DOCKER_STACK_FILE: "deploy/postgres/postgres-compose.yml"
            HOST: ${{ vars.DEPLOY_HOST }}
            USER: ${{ vars.SETUP_USER }}
            PORT: ${{ vars.DEPLOY_PORT }}
            SSH_KEY: ${{ secrets.SETUP_SSH_KEY }}
            DATA_VOLUME: "${{ vars.DATA_VOLUME }}/data/postgres"
            CONF_VOLUME: "${{ vars.DATA_VOLUME }}/conf/postgres"
            PGUID: ${{ vars.PGUID }}
            PGGID: ${{ vars.PGGID }}
            POSTGRES_USER: ${{ vars.POSTGRES_USER }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB }}
            POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
            POSTGRES_IMAGE: ${{ vars.POSTGRES_IMAGE }}
            POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
            APP_DB_USERNAME: ${{ vars.APP_DB_USERNAME }}
            APP_DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
            APP_DB_NAME: ${{ vars.APP_DB_NAME }}


        steps:
        - name: ssh setup
          run: |
            mkdir -p "$HOME/.ssh"
            KEY_FILE="$HOME/.ssh/id_ed25519"

            echo "${SSH_KEY}" > "$KEY_FILE"

            echo "SSH_KEY_FILE=$KEY_FILE" >> "$GITHUB_ENV"

            chmod 400 "$KEY_FILE"
        - name: checkout code
          uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # @v6
          with:
            fetch-depth: 0
            persist-credentials: false

        - name: sanitize and config environment
          shell: bash
          run: |
            DATA_VOLUME=$(echo "$DATA_VOLUME" | tr -d '\r')
            CONF_VOLUME=$(echo "$CONF_VOLUME" | tr -d '\r')
            PGUID=$(echo "${PGUID}" | tr -d '\r')
            PGGID=$(echo "${PGGID}" | tr -d '\r')
            STACK_NAME=$(echo "${STACK_NAME}" | tr -d '\r')

            echo "DATA_VOLUME=$DATA_VOLUME" >> "$GITHUB_ENV"
            echo "CONF_VOLUME=$CONF_VOLUME" >> "$GITHUB_ENV"
            echo "PGUID=$PGUID" >> "$GITHUB_ENV"
            echo "PGGID=$PGGID" >> "$GITHUB_ENV"
            echo "STACK_NAME=$STACK_NAME" >> "$GITHUB_ENV"

            envsubst < "${DOCKER_STACK_FILE}" | docker stack config -c -

        - name: stack deploy
          shell: bash
          run: |
            mkdir -p "$HOME/.ssh"
            cat << EOL >> "$HOME/.ssh/config"
            Host ngrok-vbt
                HostName ${HOST}
                Port ${PORT}
                User ${USER}
                IdentityFile ${SSH_KEY_FILE}
                StrictHostKeyChecking no
                UserKnownHostsFile /dev/null
            EOL

            export DOCKER_HOST="ssh://ngrok-vbt"

            docker network inspect prod_infra-net >/dev/null 2>&1 || \
            docker network create --driver overlay prod_infra-net

            envsubst < "${DOCKER_STACK_FILE}" | docker stack deploy --with-registry-auth -c - "${STACK_NAME}"
            docker stack ls
            docker stack ps "${STACK_NAME}"